name: Projet Asmtariste - CI/CD

on:
  push:
    branches: [ staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Install Angular CLI
      run: npm install -g @angular/cli
    
    - name: Run unit tests
      run: ng test --watch=false --browsers=ChromeHeadless

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Install Angular CLI
      run: npm install -g @angular/cli
    
    - name: Build Angular app
      run: ng build --configuration production

    - name: Check build output
      run: ls -la dist/dashboard/browser
    
    # Déploiement staging
    - name: Deploy to Staging
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /dashboard-staging.asmtariste.fr/